// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUrl(arg1) {
  return window['go']['main']['App']['AddUrl'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function GetUrls() {
  return window['go']['main']['App']['GetUrls']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveUrl(arg1) {
  return window['go']['main']['App']['RemoveUrl'](arg1);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
