// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUrl(arg1) {
  return window['go']['main']['App']['AddUrl'](arg1);
}

export function CancelFFmpegDownload() {
  return window['go']['main']['App']['CancelFFmpegDownload']();
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFFmpegDownloadProgress() {
  return window['go']['main']['App']['GetFFmpegDownloadProgress']();
}

export function GetFFmpegInfo() {
  return window['go']['main']['App']['GetFFmpegInfo']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function GetUrls() {
  return window['go']['main']['App']['GetUrls']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveHistoryItem(arg1) {
  return window['go']['main']['App']['RemoveHistoryItem'](arg1);
}

export function RemoveUrl(arg1) {
  return window['go']['main']['App']['RemoveUrl'](arg1);
}

export function RestoreWindowState() {
  return window['go']['main']['App']['RestoreWindowState']();
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function StartAppUpdate(arg1) {
  return window['go']['main']['App']['StartAppUpdate'](arg1);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function ToggleMiniMode(arg1) {
  return window['go']['main']['App']['ToggleMiniMode'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
