// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Configuration>;

export function GetRecordingStatus():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function StartRecording(arg1:string):Promise<string>;

export function StopRecording(arg1:string):Promise<string>;
