// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {recorder} from '../models';

export function AddUrl(arg1:string):Promise<string>;

export function CancelFFmpegDownload():Promise<void>;

export function CheckFFmpeg():Promise<boolean>;

export function DownloadFFmpeg():Promise<string>;

export function GetConfig():Promise<config.Configuration>;

export function GetFFmpegDownloadProgress():Promise<Record<string, any>>;

export function GetFFmpegInfo():Promise<string>;

export function GetHistory():Promise<Array<config.HistoryItem>>;

export function GetRecordingStatus():Promise<Array<recorder.ActiveRecording>>;

export function GetUrls():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveHistoryItem(arg1:string):Promise<string>;

export function RemoveUrl(arg1:string):Promise<string>;

export function SaveWindowState():Promise<void>;

export function StartRecording(arg1:string):Promise<string>;

export function StopRecording(arg1:string):Promise<string>;

export function ToggleMiniMode(arg1:boolean):Promise<void>;

export function UpdateConfig(arg1:config.Configuration):Promise<string>;
